parameters:
  - name: Simple
    type: string
    default: "Hello World"
  - name: Complex
    type: object
    default:
      - Build
  - name: Complex2
    type: object
    default:
      - Build
      - Second
  - name: Complex3
    type: object
    default:
      - Second
      - Third

trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Stage1
    jobs:
      - job: Build
        displayName: "Build job"
        steps:
          - script: |
              echo $Simple
              echo "##vso[task.setvariable variable=SimpleSimon;isOutput=true]Pie man"
              echo "##vso[task.setvariable variable=DependsOn;isOutput=true]Stage2Job1"
            displayName: "Run a one-line script"
            name: Step1
            env:
              Simple: ${{ parameters.Simple }}

      - job: Second
        displayName: "Second job"
        dependsOn: ${{ parameters.Complex }}

        steps:
          - script: echo $(Simple)
            displayName: "Run a one-line script"

      - job: Third
        displayName: "Third job"
        dependsOn: ${{ parameters.Complex2 }}

        steps:
          - script: echo $(Simple)
            displayName: "Run a one-line script"

      - job: Fourth
        displayName: "Fourth job"
        dependsOn:
          - Build
          - ${{ each item in parameters.Complex3 }}:
              - ${{ item }}

        steps:
          - script: echo $(Simple)
            displayName: "Run a one-line script"

  - stage: Stage2
    dependsOn: Stage1
    variables:
      SimpleSimon: $[ stageDependencies.Stage1.Build.outputs['Step1.SimpleSimon'] ]
      stageDependencies: $[ convertToJson(stageDependencies) ]
      Dependencies: $[ stageDependencies.Stage1.Build.outputs['Step1.DependsOn'] ]

    jobs:
      - job: Stage2Job1
        displayName: "Stage 2 Job 1"
        steps:
          - script: echo $(SimpleSimon)
            displayName: "Run a one-line script"

      - template: template.yml
        parameters:
          Simple: $(SimpleSimon)
          DependsOn: $(Dependencies) # Can we use this to define the dependencies for the job?
