parameters:
  - name: Simple
    type: string
    default: "Hello World"
  - name: Complex
    type: object
    default:
      - Build
  - name: Complex2
    type: object
    default:
      - Build
      - Second
  - name: Complex3
    type: object
    default:
      - Second
      - Third

trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Stage1
    jobs:
      - job: Build
        displayName: "Build job"
        steps:
          - script: |
              echo $(Simple)
              echo "##vso[task.setvariable variable=SimpleSimon;isOutput=true]Pie man"
            displayName: "Run a one-line script"
            name: Step1
            env:
              Simple: ${{ parameters.Simple }}

      - job: Second
        displayName: "Second job"
        dependsOn: ${{ parameters.Complex }}

        steps:
          - script: echo $(Simple)
            displayName: "Run a one-line script"

      - job: Third
        displayName: "Third job"
        dependsOn: ${{ parameters.Complex2 }}

        steps:
          - script: echo $(Simple)
            displayName: "Run a one-line script"

      - job: Fourth
        displayName: "Fourth job"
        dependsOn:
          - Build
          - ${{ each item in parameters.Complex3 }}:
              - ${{ item }}

        steps:
          - script: echo $(Simple)
            displayName: "Run a one-line script"

  - stage: Stage2
    dependsOn: Stage1
    variables:
      Simple: $[ stageDependencies.Stage1.Build.outputs['Build.Step1.SimpleSimon'] ]
    jobs:
      - template: template.yml
        parameters:
          Simple: $(Simple) # This won't work!
