parameters:
  - name: Simple
    type: string
    default: 'Hello World'
  - name: Complex
    type: object
    default:
      - Build

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Build
  displayName: 'Build job'
  steps:
  - script: echo $(Simple)
    displayName: 'Run a one-line script'
    env:
      Simple: ${{ parameters.Simple }}

- job: Second
  displayName: 'Second job'
  dependsOn:
    ${{ parameters.Complex }}

  steps:
  - script: echo $(Simple)
    displayName: 'Run a one-line script'
