parameters:
  - name: Simple
    type: string
    default: "Hello World"
  - name: Complex
    type: object
    default:
      - Build
  - name: Complex2
    type: object
    default:
      - name: Build
        extra: thing
      - name: Second
        extra: thing2
  - name: Complex3
    type: object
    default:
      - Second
      - Third

trigger:
  - main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Build
    displayName: "Build job"
    steps:
      - checkout: none
      - script: echo $(Simple)
        displayName: "Run a one-line script"
        env:
          Simple: ${{ parameters.Simple }}

  - job: Second
    displayName: "Second job"
    dependsOn: ${{ parameters.Complex }}

    steps:
      - checkout: none
      - script: echo $(Simple)
        displayName: "Run a one-line script"

  - job: Third
    displayName: "Third job ${{ parameters.Complex2[1].name }}"

    steps:
      - checkout: none
      - script: echo $(Simple)
        displayName: "Run a one-line script"

  - job: Fourth
    displayName: "Fourth job"
    dependsOn:
      - Build
      - ${{ each item in parameters.Complex3 }}:
          - ${{ item }}

    steps:
      - checkout: none
      - script: echo $(Simple)
        displayName: "Run a one-line script"

  - job: Fifth
    displayName: "Fifth job"

    steps:
      - checkout: none
      - template: template.yml
        parameters:
          Complex: ${{ parameters.Complex2[0] }}
